
title: SDL Sopwith
description: >- # this means to ignore newlines until "baseurl:"
  Modern port of the classic biplane shoot-em up, Sopwith.
baseurl: /sdl-sopwith
url: https://fragglet.github.io
image: /sdl-sopwith/img/start-screen-wide.png
favicon: /sdl-sopwith/icon.png

# Build settings
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

